name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: Generate the build system
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: cmake --build build
